//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 05:42:47 PM IST 
//


package com.yash.ecom.server.ws;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productWeight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productHeight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productDepth" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="productWidth" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productWeight",
    "productHeight",
    "productDepth",
    "productWidth"
})
@XmlRootElement(name = "getShipment")
public class GetShipment {

    @XmlElement(required = true)
    public String productWeight;
    @XmlElement(required = true)
    public String productHeight;
    @XmlElement(required = true)
    public String productDepth;
    @XmlElement(required = true)
    public String productWidth;

    /**
     * Gets the value of the productWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductWeight() {
        return productWeight;
    }

    /**
     * Sets the value of the productWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductWeight(String value) {
        this.productWeight = value;
    }

    /**
     * Gets the value of the productHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductHeight() {
        return productHeight;
    }

    /**
     * Sets the value of the productHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductHeight(String value) {
        this.productHeight = value;
    }

    /**
     * Gets the value of the productDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDepth() {
        return productDepth;
    }

    /**
     * Sets the value of the productDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDepth(String value) {
        this.productDepth = value;
    }

    /**
     * Gets the value of the productWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductWidth() {
        return productWidth;
    }

    /**
     * Sets the value of the productWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductWidth(String value) {
        this.productWidth = value;
    }

}
