export const environment = {
  production: false,
  initializeCart: 'http://localhost:8081/api/cart/init',
  productSearch: 'http://localhost:8081/api/cart/search',
  incidents: 'http://localhost:8081/api/logticket',
  updateCart: 'http://localhost:8081/api/cart/refresh',
  getShipmentDetails: 'http://localhost:8081/api/cart/freight',
  order: 'http://localhost:8081/api/order/create',
  getOrder: 'http://localhost:8083/v1/sys/api/order',
  getUserOrder: 'http://localhost:8081/api/order/list',
  invoiceUrl: 'http://localhost:8081/api/invoice',
  serverLogin: `http://localhost:8080/login`,
  partyDetails: 'http://localhost:8080/api/party/all',
  userDetails: `https://dev-589498.okta.com/oauth2/default/v1/userinfo`,
};
